# Generated by Django 3.0.4 on 2020-05-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('placa', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('SOAT', models.IntegerField(blank=True, default=None)),
                ('noRevisionTM', models.IntegerField(blank=True, default=None)),
                ('camionero', models.IntegerField(default=None)),
            ],
        ),
    ]
