# Generated by Django 3.0.6 on 2020-05-29 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Producto', '0002_auto_20200528_1252'),
        ('Pedido', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cantidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroProductos', models.FloatField(max_length=100)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cantidades', to='Pedido.Pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cantidades', to='Producto.ProductosTienda')),
            ],
        ),
    ]
