# Generated by Django 3.0.4 on 2020-05-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.FloatField(blank=True, default=None, primary_key=True, serialize=False)),
                ('telefono', models.FloatField(blank=True, default=None, null=True)),
                ('contrasena', models.CharField(max_length=100)),
                ('bitacora', models.CharField(max_length=500)),
            ],
        ),
    ]
