# Generated by Django 3.0.4 on 2020-05-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductosTienda',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('EAN', models.FloatField(blank=True, default=None, primary_key=True, serialize=False)),
                ('precioCompra', models.FloatField(default=None, max_length=100)),
                ('precioVenta', models.FloatField(default=None, max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('rentability', models.IntegerField(default=None)),
            ],
        ),
    ]
