# Generated by Django 3.0.4 on 2020-05-28 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productostienda',
            old_name='precioCompra',
            new_name='precio',
        ),
        migrations.RemoveField(
            model_name='productostienda',
            name='precioVenta',
        ),
        migrations.RemoveField(
            model_name='productostienda',
            name='rentability',
        ),
    ]
