# Generated by Django 3.0.4 on 2020-05-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TiendaDeBarrio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.FloatField(blank=True, default=None, null=True)),
                ('contrasena', models.CharField(max_length=100)),
                ('nit', models.FloatField(blank=True, default=None, editable=False, null=True, unique=True)),
                ('direccion', models.CharField(max_length=500)),
            ],
        ),
    ]
